import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Listing, ListingPage, ListingStatus, SearchListingParams } from '../models/listing.model';
import { ApiResponse } from '../../../core/models/api-response.model';

@Injectable({
  providedIn: 'root'
})
export class MockListingService {
  private mockListings: Listing[] = [
    {
      publicId: 'lst-001',
      landlordPublicId: 'usr-001',
      title: 'Luxury Beachfront Villa in Malibu',
      description: 'Experience the ultimate coastal living in this stunning beachfront villa. Wake up to breathtaking ocean views, enjoy private beach access, and relax in the infinity pool overlooking the Pacific. This modern architectural masterpiece features floor-to-ceiling windows, an open-concept design, and luxurious amenities throughout. Perfect for families or groups seeking an unforgettable beach getaway.',
      location: 'Malibu',
      city: 'Malibu',
      country: 'United States',
      latitude: 34.0259,
      longitude: -118.7798,
      address: '123 Pacific Coast Highway, Malibu, CA 90265',
      pricePerNight: 850,
      currency: 'USD',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 4.5,
      propertyType: 'Villa',
      category: 'Beachfront',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Beach access', 'Parking', 'Ocean view', 'Hot tub', 'BBQ grill', 'Gym'],
      houseRules: 'No smoking, No parties, Check-in after 3 PM, Check-out before 11 AM',
      cancellationPolicy: 'Free cancellation up to 7 days before check-in',
      minimumStay: 2,
      maximumStay: 30,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop', caption: 'Ocean View Living Room', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop', caption: 'Master Bedroom', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Infinity Pool', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop', caption: 'Modern Kitchen', isCover: false, sortOrder: 4 },
        { url: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=1200&h=800&fit=crop', caption: 'Sunset Terrace', isCover: false, sortOrder: 5 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 127,
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-12-01T15:30:00Z'
    },
    {
      publicId: 'lst-002',
      landlordPublicId: 'usr-002',
      title: 'Cozy Mountain Cabin in Aspen',
      description: 'Escape to this charming mountain retreat nestled in the heart of Aspen. This rustic yet modern cabin offers the perfect blend of comfort and adventure. Featuring exposed wooden beams, a stone fireplace, and panoramic mountain views, this property is ideal for skiing enthusiasts and nature lovers. The cabin includes a fully equipped kitchen, spacious living areas, and a private hot tub on the deck.',
      location: 'Aspen',
      city: 'Aspen',
      country: 'United States',
      latitude: 39.1911,
      longitude: -106.8175,
      address: '456 Mountain Trail, Aspen, CO 81611',
      pricePerNight: 425,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 4,
      bathrooms: 2,
      propertyType: 'Cabin',
      category: 'Countryside',
      amenities: ['WiFi', 'Fireplace', 'Kitchen', 'Heating', 'Mountain view', 'Parking', 'Hot tub', 'Ski storage', 'Washer', 'Dryer'],
      houseRules: 'No smoking, Pets allowed with fee, Quiet hours 10 PM - 8 AM',
      cancellationPolicy: 'Moderate: Full refund 5 days prior to arrival',
      minimumStay: 3,
      maximumStay: 14,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop', caption: 'Mountain Cabin Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Cozy Living Room', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop', caption: 'Bedroom with Mountain View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1200&h=800&fit=crop', caption: 'Rustic Kitchen', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 89,
      createdAt: '2024-02-20T14:00:00Z',
      updatedAt: '2024-11-28T09:15:00Z'
    },
    {
      publicId: 'lst-003',
      landlordPublicId: 'usr-003',
      title: 'Modern Downtown Loft in NYC',
      description: 'Stay in the heart of Manhattan in this sleek, contemporary loft. Perfect for business travelers and urban explorers, this stylish space features exposed brick, high ceilings, and industrial-chic design. Located within walking distance of Times Square, Central Park, and world-class dining and shopping. The loft includes a fully equipped kitchen, dedicated workspace, and premium amenities.',
      location: 'Manhattan',
      city: 'New York',
      country: 'United States',
      latitude: 40.7580,
      longitude: -73.9855,
      address: '789 Broadway, New York, NY 10003',
      pricePerNight: 295,
      currency: 'USD',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
      propertyType: 'Loft',
      category: 'City',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Elevator', 'City view', 'Workspace', 'Smart TV', 'Coffee maker', 'Keyless entry'],
      houseRules: 'No smoking, No pets, No parties',
      cancellationPolicy: 'Strict: 50% refund up to 1 week before check-in',
      minimumStay: 1,
      maximumStay: 30,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop', caption: 'Modern Loft Interior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop', caption: 'Open Kitchen', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop', caption: 'Master Suite', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop', caption: 'City View', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop',
      averageRating: 4.7,
      totalReviews: 213,
      createdAt: '2024-03-10T11:00:00Z',
      updatedAt: '2024-12-05T16:45:00Z'
    },
    {
      publicId: 'lst-004',
      landlordPublicId: 'usr-004',
      title: 'Tropical Paradise Villa in Bali',
      description: 'Immerse yourself in luxury at this stunning tropical villa surrounded by lush rice paddies and jungle views. This Balinese-style property features traditional architecture with modern amenities, including a private pool, outdoor shower, and expansive terrace. Perfect for couples or small families seeking tranquility and authentic Balinese hospitality. Located near Ubud\'s cultural attractions and world-class restaurants.',
      location: 'Ubud',
      city: 'Ubud',
      country: 'Indonesia',
      latitude: -8.5069,
      longitude: 115.2625,
      address: 'Jl. Raya Ubud No. 88, Ubud, Bali 80571',
      pricePerNight: 185,
      currency: 'USD',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
      propertyType: 'Villa',
      category: 'Tropical',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Garden view', 'Parking', 'Outdoor shower', 'Yoga space', 'Daily cleaning'],
      houseRules: 'No smoking indoors, Respectful of local culture',
      cancellationPolicy: 'Flexible: Full refund 1 day prior to arrival',
      minimumStay: 2,
      maximumStay: 30,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=1200&h=800&fit=crop', caption: 'Tropical Villa Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=1200&h=800&fit=crop', caption: 'Private Pool', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Luxurious Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&h=800&fit=crop', caption: 'Open-air Bathroom', isCover: false, sortOrder: 4 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Rice Paddy View', isCover: false, sortOrder: 5 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 156,
      createdAt: '2024-04-05T08:00:00Z',
      updatedAt: '2024-12-03T12:20:00Z'
    },
    {
      publicId: 'lst-005',
      landlordPublicId: 'usr-005',
      title: 'Historic Parisian Apartment with Eiffel Tower View',
      description: 'Experience authentic Parisian living in this beautifully renovated 19th-century apartment. Located in the prestigious 7th arrondissement, this elegant space offers stunning views of the Eiffel Tower from the balcony. Featuring original parquet floors, high ceilings with ornate moldings, and a mix of classic French charm with modern comfort. Walking distance to museums, cafes, and the Seine River.',
      location: 'Paris 7th',
      city: 'Paris',
      country: 'France',
      latitude: 48.8566,
      longitude: 2.3522,
      address: '12 Avenue de la Bourdonnais, 75007 Paris',
      pricePerNight: 385,
      currency: 'EUR',
      maxGuests: 5,
      bedrooms: 2,
      beds: 3,
      bathrooms: 1,
      propertyType: 'Apartment',
      category: 'City',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Eiffel Tower view', 'Balcony', 'Washer', 'Elevator', 'Coffee maker', 'Wine glasses'],
      houseRules: 'No smoking, No parties, Quiet hours 10 PM - 8 AM',
      cancellationPolicy: 'Moderate: Full refund 5 days prior to arrival',
      minimumStay: 3,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=1200&h=800&fit=crop', caption: 'Parisian Living Room', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=1200&h=800&fit=crop', caption: 'Eiffel Tower View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1200&h=800&fit=crop', caption: 'Classic Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1200&h=800&fit=crop', caption: 'French Kitchen', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 94,
      createdAt: '2024-05-12T13:00:00Z',
      updatedAt: '2024-11-30T10:30:00Z'
    },
    {
      publicId: 'lst-006',
      landlordPublicId: 'usr-006',
      title: 'Seaside Cottage in Santorini',
      description: 'Discover the magic of Santorini in this traditional Cycladic cottage perched on the caldera cliff. Whitewashed walls, blue-domed architecture, and breathtaking sunset views over the Aegean Sea create an unforgettable Greek island experience. The cottage features a private terrace, outdoor dining area, and modern amenities while maintaining authentic island charm. Perfect for romantic getaways.',
      location: 'Oia',
      city: 'Santorini',
      country: 'Greece',
      latitude: 36.4618,
      longitude: 25.3753,
      address: 'Oia Main Street, Santorini 84702',
      pricePerNight: 320,
      currency: 'EUR',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'Cottage',
      category: 'Beachfront',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Sea view', 'Terrace', 'Outdoor dining', 'Sunset view', 'Wine cellar'],
      houseRules: 'No smoking, No pets, Romantic retreat - adults only',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=1200&h=800&fit=crop', caption: 'Santorini Sunset View', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Cozy Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Private Terrace', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop', caption: 'Cycladic Kitchen', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 78,
      createdAt: '2024-06-18T09:00:00Z',
      updatedAt: '2024-12-02T14:10:00Z'
    },
    {
      publicId: 'lst-007',
      landlordPublicId: 'usr-007',
      title: 'Safari Lodge in Serengeti National Park',
      description: 'Experience the African wilderness in this luxury safari lodge overlooking the vast Serengeti plains. Watch wildlife from your private deck, enjoy sundowners by the fire pit, and fall asleep to the sounds of nature. This eco-friendly lodge combines rustic elegance with modern comfort, featuring en-suite bathrooms, gourmet meals, and guided safari tours. An adventure of a lifetime awaits.',
      location: 'Serengeti',
      city: 'Serengeti',
      country: 'Tanzania',
      latitude: -2.3333,
      longitude: 34.8333,
      address: 'Serengeti National Park, Tanzania',
      pricePerNight: 550,
      currency: 'USD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'Lodge',
      category: 'Countryside',
      amenities: ['WiFi', 'Restaurant', 'Bar', 'Wildlife view', 'Safari tours', 'Fire pit', 'Outdoor shower', 'Laundry service', 'All meals included'],
      houseRules: 'Follow safari guide instructions, Wildlife safety protocols apply',
      cancellationPolicy: 'Moderate: 50% refund 14 days prior to arrival',
      minimumStay: 3,
      maximumStay: 10,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop', caption: 'Safari Lodge Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Luxury Tent Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&h=800&fit=crop', caption: 'Serengeti View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=800&fit=crop', caption: 'Sunset Deck', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 45,
      createdAt: '2024-07-22T07:00:00Z',
      updatedAt: '2024-11-25T11:50:00Z'
    },
    {
      publicId: 'lst-008',
      landlordPublicId: 'usr-008',
      title: 'Lake House Retreat in Lake Como',
      description: 'Relax in this elegant lakefront property on the shores of Lake Como, Italy. This beautifully restored villa offers panoramic lake and mountain views, a private dock, and lush gardens. Features include marble floors, antique furnishings, a gourmet kitchen, and multiple terraces perfect for al fresco dining. Close to charming villages, upscale boutiques, and excellent restaurants.',
      location: 'Bellagio',
      city: 'Como',
      country: 'Italy',
      latitude: 45.9771,
      longitude: 9.2577,
      address: 'Via Regina 100, 22021 Bellagio CO',
      pricePerNight: 675,
      currency: 'EUR',
      maxGuests: 10,
      bedrooms: 5,
      beds: 6,
      bathrooms: 4,
      propertyType: 'Villa',
      category: 'Lakefront',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Lake view', 'Parking', 'Garden', 'Private dock', 'Boat rental', 'BBQ grill', 'Wine cellar'],
      houseRules: 'No smoking indoors, Events allowed with prior approval',
      cancellationPolicy: 'Strict: 50% refund up to 2 weeks before check-in',
      minimumStay: 4,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop', caption: 'Lake Como Villa', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1200&h=800&fit=crop', caption: 'Elegant Living Room', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop', caption: 'Lakefront Terrace', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1200&h=800&fit=crop', caption: 'Master Suite', isCover: false, sortOrder: 4 },
        { url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1200&h=800&fit=crop', caption: 'Gourmet Kitchen', isCover: false, sortOrder: 5 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 112,
      createdAt: '2024-08-14T12:00:00Z',
      updatedAt: '2024-12-04T13:25:00Z'
    },
    // Amazing views
    {
      publicId: 'lst-009',
      landlordPublicId: 'usr-009',
      title: 'Cliffside Villa with Panoramic Mountain Views',
      description: 'Perched on a dramatic cliff edge, this architectural masterpiece offers breathtaking 360-degree views of the surrounding mountain ranges and valleys. Floor-to-ceiling windows frame nature\'s grandeur, while the infinity pool seems to merge with the horizon. Perfect for those seeking inspiration and tranquility in an awe-inspiring setting.',
      location: 'Big Sur',
      city: 'Big Sur',
      country: 'United States',
      latitude: 36.2704,
      longitude: -121.8081,
      address: '1 Cliffside Drive, Big Sur, CA 93920',
      pricePerNight: 950,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 3,
      bathrooms: 3,
      propertyType: 'Villa',
      category: 'Amazing views',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Mountain view', 'Ocean view', 'Hot tub', 'Fireplace', 'Parking', 'BBQ grill'],
      houseRules: 'No smoking, No parties, Quiet hours 10 PM - 8 AM',
      cancellationPolicy: 'Moderate: Full refund 5 days prior to arrival',
      minimumStay: 2,
      maximumStay: 30,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop', caption: 'Panoramic View', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Living Area', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1200&h=800&fit=crop', caption: 'Master Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Infinity Pool', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 85,
      createdAt: '2024-09-01T10:00:00Z',
      updatedAt: '2024-12-06T08:30:00Z'
    },
    {
      publicId: 'lst-010',
      landlordPublicId: 'usr-010',
      title: 'Glass House in the Alps',
      description: 'Experience unparalleled views of the Swiss Alps from this stunning glass-walled residence. Watch the sunrise paint the mountains in gold, and stargaze from your bedroom at night. This modern architectural wonder seamlessly blends luxury with nature, featuring heated floors, a sauna, and premium amenities throughout.',
      location: 'Zermatt',
      city: 'Zermatt',
      country: 'Switzerland',
      latitude: 46.0207,
      longitude: 7.7491,
      address: 'Alpine Road 42, 3920 Zermatt',
      pricePerNight: 1250,
      currency: 'CHF',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 4,
      propertyType: 'House',
      category: 'Amazing views',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Mountain view', 'Sauna', 'Fireplace', 'Parking', 'Ski storage', 'Hot tub', 'Smart home'],
      houseRules: 'No smoking, No pets, Mountain safety guidelines apply',
      cancellationPolicy: 'Strict: 50% refund up to 2 weeks before check-in',
      minimumStay: 3,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop', caption: 'Alpine Vista', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop', caption: 'Glass Living Room', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop', caption: 'Mountain View Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1200&h=800&fit=crop', caption: 'Luxury Bathroom', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 67,
      createdAt: '2024-09-15T11:00:00Z',
      updatedAt: '2024-12-05T14:20:00Z'
    },
    // Trending
    {
      publicId: 'lst-011',
      landlordPublicId: 'usr-011',
      title: 'Luxury Dome with Aurora Views in Iceland',
      description: 'Stay in this Instagram-famous geodesic dome and witness the Northern Lights from your bed. This eco-luxury retreat features a transparent ceiling perfect for aurora viewing, heated floors, and a private hot tub. The dome\'s unique design has made it a trending destination for travelers seeking unforgettable experiences.',
      location: 'Reykjavik',
      city: 'Reykjavik',
      country: 'Iceland',
      latitude: 64.1466,
      longitude: -21.9426,
      address: 'Northern Lights Road 15, Reykjavik 101',
      pricePerNight: 495,
      currency: 'EUR',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Trending',
      amenities: ['WiFi', 'Heating', 'Hot tub', 'Northern Lights view', 'Stargazing', 'Eco-friendly', 'Kitchen', 'Parking'],
      houseRules: 'No smoking, No pets, Respect nature',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&h=800&fit=crop', caption: 'Dome Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=1200&h=800&fit=crop', caption: 'Aurora View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&h=800&fit=crop', caption: 'Cozy Interior', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&h=800&fit=crop', caption: 'Hot Tub', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 142,
      createdAt: '2024-09-20T09:00:00Z',
      updatedAt: '2024-12-07T10:15:00Z'
    },
    {
      publicId: 'lst-012',
      landlordPublicId: 'usr-012',
      title: 'Floating Villa in the Maldives',
      description: 'Experience the ultimate luxury in this overwater villa that\'s taken social media by storm. Direct lagoon access, private infinity pool, glass floor panels for fish watching, and unparalleled privacy. This trending property offers the perfect blend of adventure and relaxation in paradise.',
      location: 'Male Atoll',
      city: 'Male',
      country: 'Maldives',
      latitude: 4.1755,
      longitude: 73.5093,
      address: 'Overwater Villa 7, Male Atoll',
      pricePerNight: 1850,
      currency: 'USD',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
      propertyType: 'Villa',
      category: 'Trending',
      amenities: ['WiFi', 'Pool', 'Air conditioning', 'Ocean view', 'Private beach', 'Snorkeling gear', 'Kayaks', 'Butler service', 'Spa'],
      houseRules: 'No smoking, Marine conservation rules apply',
      cancellationPolicy: 'Strict: 50% refund up to 30 days before check-in',
      minimumStay: 3,
      maximumStay: 14,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop', caption: 'Overwater Villa', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&h=800&fit=crop', caption: 'Private Pool', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&h=800&fit=crop', caption: 'Glass Floor', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1540202404-d0c7fe46a087?w=1200&h=800&fit=crop', caption: 'Sunset View', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 198,
      createdAt: '2024-10-01T08:00:00Z',
      updatedAt: '2024-12-08T09:45:00Z'
    },
    // Cabins
    {
      publicId: 'lst-013',
      landlordPublicId: 'usr-013',
      title: 'Rustic Log Cabin in the Smokies',
      description: 'Escape to this authentic log cabin nestled in the Great Smoky Mountains. Featuring hand-hewn logs, a stone fireplace, and a wraparound porch with rocking chairs. Perfect for unplugging and reconnecting with nature. Enjoy hiking trails, wildlife viewing, and peaceful mountain evenings.',
      location: 'Gatlinburg',
      city: 'Gatlinburg',
      country: 'United States',
      latitude: 35.7143,
      longitude: -83.5102,
      address: 'Mountain Trail Road 88, Gatlinburg, TN 37738',
      pricePerNight: 285,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 4,
      bathrooms: 2,
      propertyType: 'Cabin',
      category: 'Cabins',
      amenities: ['WiFi', 'Fireplace', 'Kitchen', 'Heating', 'Mountain view', 'Parking', 'Hot tub', 'BBQ grill', 'Washer', 'Dryer'],
      houseRules: 'No smoking, Pets allowed with fee, Quiet hours 10 PM - 7 AM',
      cancellationPolicy: 'Flexible: Full refund 2 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=800&fit=crop', caption: 'Log Cabin Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1475855581690-80accde3ae2b?w=1200&h=800&fit=crop', caption: 'Cozy Living Room', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop', caption: 'Rustic Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1464146072230-91cabc968266?w=1200&h=800&fit=crop', caption: 'Porch View', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 156,
      createdAt: '2024-10-05T10:00:00Z',
      updatedAt: '2024-12-06T11:30:00Z'
    },
    {
      publicId: 'lst-014',
      landlordPublicId: 'usr-014',
      title: 'Modern Cabin Retreat in the Canadian Rockies',
      description: 'This contemporary cabin blends modern luxury with wilderness charm. Floor-to-ceiling windows showcase stunning mountain vistas, while the minimalist interior features premium finishes, a gourmet kitchen, and spa-like bathrooms. Located near world-class skiing, hiking, and the charming town of Banff.',
      location: 'Banff',
      city: 'Banff',
      country: 'Canada',
      latitude: 51.1784,
      longitude: -115.5708,
      address: 'Rocky Mountain Road 234, Banff, AB T1L 1A1',
      pricePerNight: 525,
      currency: 'CAD',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 3,
      propertyType: 'Cabin',
      category: 'Cabins',
      amenities: ['WiFi', 'Fireplace', 'Kitchen', 'Heating', 'Mountain view', 'Parking', 'Hot tub', 'Sauna', 'Ski storage', 'Smart home'],
      houseRules: 'No smoking, No pets, Bear-safe food storage required',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 3,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop', caption: 'Mountain Cabin', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop', caption: 'Modern Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop', caption: 'Luxury Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop', caption: 'Rocky View', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 91,
      createdAt: '2024-10-10T09:00:00Z',
      updatedAt: '2024-12-07T12:00:00Z'
    },
    // Mansions
    {
      publicId: 'lst-015',
      landlordPublicId: 'usr-015',
      title: 'Beverly Hills Mega Mansion',
      description: 'Live like a celebrity in this 15,000 sq ft mansion in the heart of Beverly Hills. Features include a home theater, wine cellar, gym, spa, infinity pool with city views, and 8-car garage. The property boasts designer furnishings, smart home technology, and impeccable landscaping. Perfect for luxury retreats and special events.',
      location: 'Beverly Hills',
      city: 'Los Angeles',
      country: 'United States',
      latitude: 34.0736,
      longitude: -118.4004,
      address: '90210 Sunset Boulevard, Beverly Hills, CA 90210',
      pricePerNight: 3500,
      currency: 'USD',
      maxGuests: 16,
      bedrooms: 8,
      beds: 10,
      bathrooms: 10,
      propertyType: 'House',
      category: 'Mansions',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'City view', 'Parking', 'Gym', 'Home theater', 'Wine cellar', 'Smart home', 'Security system', 'Chef kitchen'],
      houseRules: 'No smoking, Events allowed with approval, Security deposit required',
      cancellationPolicy: 'Strict: 50% refund up to 30 days before check-in',
      minimumStay: 3,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop', caption: 'Mansion Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop', caption: 'Grand Foyer', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop', caption: 'Infinity Pool', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&h=800&fit=crop', caption: 'Master Suite', isCover: false, sortOrder: 4 },
        { url: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=1200&h=800&fit=crop', caption: 'Home Theater', isCover: false, sortOrder: 5 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 43,
      createdAt: '2024-10-12T13:00:00Z',
      updatedAt: '2024-12-08T15:20:00Z'
    },
    {
      publicId: 'lst-016',
      landlordPublicId: 'usr-016',
      title: 'Historic French Chateau Estate',
      description: 'Own a piece of history in this magnificent 18th-century chateau set on 50 acres of manicured gardens and vineyards. The estate features original frescoes, antique furnishings, formal dining rooms, and a private chapel. Modern amenities have been seamlessly integrated while preserving the property\'s authentic charm.',
      location: 'Loire Valley',
      city: 'Tours',
      country: 'France',
      latitude: 47.3941,
      longitude: 0.6848,
      address: 'Château Route 1, 37000 Tours',
      pricePerNight: 4200,
      currency: 'EUR',
      maxGuests: 20,
      bedrooms: 10,
      beds: 12,
      bathrooms: 8,
      propertyType: 'House',
      category: 'Mansions',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Garden view', 'Parking', 'Wine cellar', 'Library', 'Formal gardens', 'Piano', 'Staff quarters', 'Event space'],
      houseRules: 'No smoking indoors, Events welcome, Respectful of historic property',
      cancellationPolicy: 'Strict: 50% refund up to 60 days before check-in',
      minimumStay: 4,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop', caption: 'Chateau Facade', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&h=800&fit=crop', caption: 'Grand Salon', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&h=800&fit=crop', caption: 'Formal Gardens', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1618945524163-32451704c25e?w=1200&h=800&fit=crop', caption: 'Library', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 28,
      createdAt: '2024-10-15T14:00:00Z',
      updatedAt: '2024-12-09T10:30:00Z'
    },
    // Design
    {
      publicId: 'lst-017',
      landlordPublicId: 'usr-017',
      title: 'Award-Winning Minimalist House in Tokyo',
      description: 'Experience Japanese design excellence in this award-winning minimalist residence. Clean lines, natural materials, and thoughtful spatial design create a serene urban oasis. Featured in architectural magazines, this home showcases sliding shoji screens, a zen garden, and cutting-edge sustainable technology.',
      location: 'Shibuya',
      city: 'Tokyo',
      country: 'Japan',
      latitude: 35.6595,
      longitude: 139.7004,
      address: '2-21-1 Shibuya, Tokyo 150-0002',
      pricePerNight: 625,
      currency: 'JPY',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
      propertyType: 'House',
      category: 'Design',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'City view', 'Zen garden', 'Smart home', 'Minimalist design', 'Eco-friendly', 'Workspace'],
      houseRules: 'No smoking, No shoes indoors, Respect minimalist aesthetic',
      cancellationPolicy: 'Moderate: Full refund 5 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&h=800&fit=crop', caption: 'Minimalist Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&h=800&fit=crop', caption: 'Zen Living Space', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=1200&h=800&fit=crop', caption: 'Japanese Garden', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&h=800&fit=crop', caption: 'Clean Bedroom', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 74,
      createdAt: '2024-10-18T11:00:00Z',
      updatedAt: '2024-12-08T13:45:00Z'
    },
    {
      publicId: 'lst-018',
      landlordPublicId: 'usr-018',
      title: 'Bauhaus-Inspired Desert Residence',
      description: 'Stay in this stunning example of modern desert architecture. This Bauhaus-inspired home features geometric forms, a monochromatic palette, and seamless indoor-outdoor living. The design incorporates passive cooling, solar panels, and xeriscaping, making it both beautiful and sustainable.',
      location: 'Palm Springs',
      city: 'Palm Springs',
      country: 'United States',
      latitude: 33.8303,
      longitude: -116.5453,
      address: '456 Modernist Way, Palm Springs, CA 92262',
      pricePerNight: 725,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 3,
      bathrooms: 3,
      propertyType: 'House',
      category: 'Design',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Mountain view', 'Parking', 'Outdoor shower', 'Fire pit', 'Solar power', 'Modern art'],
      houseRules: 'No smoking, No pets, Respect architectural features',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 21,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop', caption: 'Desert Architecture', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop', caption: 'Geometric Design', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&h=800&fit=crop', caption: 'Pool Area', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=800&fit=crop', caption: 'Interior Space', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 62,
      createdAt: '2024-10-20T10:00:00Z',
      updatedAt: '2024-12-09T09:15:00Z'
    },
    // Pools
    {
      publicId: 'lst-019',
      landlordPublicId: 'usr-019',
      title: 'Villa with Olympic-Size Pool in Ibiza',
      description: 'Make a splash in this luxurious villa featuring an Olympic-size swimming pool perfect for serious swimmers and pool parties alike. The property includes multiple sun terraces, an outdoor bar, and stunning Mediterranean views. Ideal for groups who love water activities and outdoor entertaining.',
      location: 'San Antonio',
      city: 'Ibiza',
      country: 'Spain',
      latitude: 38.9807,
      longitude: 1.3023,
      address: 'Cala Bassa Road 77, 07820 Ibiza',
      pricePerNight: 1150,
      currency: 'EUR',
      maxGuests: 12,
      bedrooms: 6,
      beds: 8,
      bathrooms: 6,
      propertyType: 'Villa',
      category: 'Pools',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Sea view', 'Parking', 'Outdoor bar', 'BBQ grill', 'Sun loungers', 'Pool toys', 'Sound system'],
      houseRules: 'No smoking indoors, Events allowed with approval, Pool safety rules apply',
      cancellationPolicy: 'Strict: 50% refund up to 2 weeks before check-in',
      minimumStay: 4,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&h=800&fit=crop', caption: 'Olympic Pool', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=1200&h=800&fit=crop', caption: 'Villa Exterior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop', caption: 'Pool Terrace', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&h=800&fit=crop', caption: 'Outdoor Living', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 118,
      createdAt: '2024-10-22T12:00:00Z',
      updatedAt: '2024-12-07T14:30:00Z'
    },
    {
      publicId: 'lst-020',
      landlordPublicId: 'usr-020',
      title: 'Tropical Estate with Natural Pool and Waterfall',
      description: 'Immerse yourself in paradise at this unique estate featuring a natural rock pool fed by a stunning waterfall. The property blends luxury with nature, offering multiple pools including an infinity edge, swim-up bar, and children\'s splash area. Surrounded by lush tropical gardens and mature palms.',
      location: 'Phuket',
      city: 'Phuket',
      country: 'Thailand',
      latitude: 7.8804,
      longitude: 98.3923,
      address: 'Kamala Beach Road 123, Phuket 83150',
      pricePerNight: 875,
      currency: 'USD',
      maxGuests: 10,
      bedrooms: 5,
      beds: 6,
      bathrooms: 5,
      propertyType: 'Villa',
      category: 'Pools',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Ocean view', 'Parking', 'Waterfall', 'Swim-up bar', 'Tropical garden', 'Outdoor dining', 'Pool service'],
      houseRules: 'No smoking, Children welcome, Pool supervision required',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 3,
      maximumStay: 28,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop', caption: 'Waterfall Pool', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1602216056808-f638a9611a8e?w=1200&h=800&fit=crop', caption: 'Infinity Edge', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop', caption: 'Tropical Setting', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1200&h=800&fit=crop', caption: 'Pool Bar', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 134,
      createdAt: '2024-10-25T09:00:00Z',
      updatedAt: '2024-12-08T11:00:00Z'
    },
    // Islands
    {
      publicId: 'lst-021',
      landlordPublicId: 'usr-021',
      title: 'Private Island Villa in the Caribbean',
      description: 'Experience ultimate privacy on your own Caribbean island. This exclusive villa offers 360-degree ocean views, private beaches, and complete seclusion. Includes a full-time staff, private chef, and boat for island hopping. Perfect for honeymoons, family reunions, or those seeking an escape from the world.',
      location: 'Exuma',
      city: 'Nassau',
      country: 'Bahamas',
      latitude: 23.5625,
      longitude: -75.9394,
      address: 'Private Island, Exuma Cays',
      pricePerNight: 5500,
      currency: 'USD',
      maxGuests: 12,
      bedrooms: 6,
      beds: 8,
      bathrooms: 6,
      propertyType: 'Villa',
      category: 'Islands',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Ocean view', 'Private beach', 'Boat', 'Snorkeling gear', 'Kayaks', 'Full staff', 'Private chef', 'Helicopter pad'],
      houseRules: 'No smoking indoors, Respect marine life, Island rules apply',
      cancellationPolicy: 'Strict: 50% refund up to 60 days before check-in',
      minimumStay: 5,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop', caption: 'Private Island', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=1200&h=800&fit=crop', caption: 'Villa Beachfront', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop', caption: 'Ocean View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop', caption: 'Private Beach', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 15,
      createdAt: '2024-10-28T10:00:00Z',
      updatedAt: '2024-12-09T12:30:00Z'
    },
    {
      publicId: 'lst-022',
      landlordPublicId: 'usr-022',
      title: 'Secluded Beach House in Seychelles',
      description: 'Discover paradise in this exclusive beach house on a pristine Seychelles island. Crystal-clear waters, powder-white sand, and lush vegetation create a tropical haven. The house features indoor-outdoor living, a private pier, and unobstructed ocean views. Perfect for diving, fishing, and total relaxation.',
      location: 'Praslin',
      city: 'Praslin',
      country: 'Seychelles',
      latitude: -4.3197,
      longitude: 55.7449,
      address: 'Anse Lazio Beach, Praslin',
      pricePerNight: 2200,
      currency: 'EUR',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 4,
      propertyType: 'House',
      category: 'Islands',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Ocean view', 'Private beach', 'Snorkeling gear', 'Fishing equipment', 'Kayaks', 'Outdoor shower', 'Hammocks', 'BBQ grill'],
      houseRules: 'No smoking, Eco-friendly practices required, Respect wildlife',
      cancellationPolicy: 'Strict: 50% refund up to 30 days before check-in',
      minimumStay: 4,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=1200&h=800&fit=crop', caption: 'Beach House', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&h=800&fit=crop', caption: 'Pristine Beach', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=1200&h=800&fit=crop', caption: 'Ocean Living', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200&h=800&fit=crop', caption: 'Island Paradise', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 37,
      createdAt: '2024-11-01T11:00:00Z',
      updatedAt: '2024-12-08T15:45:00Z'
    },
    // Caves
    {
      publicId: 'lst-023',
      landlordPublicId: 'usr-023',
      title: 'Luxury Cave Dwelling in Cappadocia',
      description: 'Stay in an authentic cave hotel carved into the fairy chimneys of Cappadocia. This unique property combines ancient architecture with modern luxury, featuring stone walls, arched ceilings, and contemporary amenities. Watch hot air balloons drift by from your private terrace while enjoying Turkish hospitality.',
      location: 'Göreme',
      city: 'Cappadocia',
      country: 'Turkey',
      latitude: 38.6431,
      longitude: 34.8286,
      address: 'Göreme Valley Road 45, 50180 Cappadocia',
      pricePerNight: 295,
      currency: 'EUR',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
      propertyType: 'House',
      category: 'Caves',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Air conditioning', 'Valley view', 'Terrace', 'Hot air balloon view', 'Turkish bath', 'Fireplace'],
      houseRules: 'No smoking, Respect historic structure, Quiet hours 10 PM - 8 AM',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&h=800&fit=crop', caption: 'Cave Hotel', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1559628376-f3fe5f782a2f?w=1200&h=800&fit=crop', caption: 'Stone Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1609219123196-c38b68fdea0c?w=1200&h=800&fit=crop', caption: 'Balloon View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop', caption: 'Cave Bedroom', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 203,
      createdAt: '2024-11-03T09:00:00Z',
      updatedAt: '2024-12-09T10:00:00Z'
    },
    {
      publicId: 'lst-024',
      landlordPublicId: 'usr-024',
      title: 'Modern Cave House in Southern Spain',
      description: 'Experience unique troglodyte living in this renovated cave house in Andalusia. Naturally insulated by the earth, these caves stay cool in summer and warm in winter. The property features whitewashed walls, colorful tiles, and a sunny courtyard with mountain views. A truly one-of-a-kind experience.',
      location: 'Guadix',
      city: 'Granada',
      country: 'Spain',
      latitude: 37.2998,
      longitude: -3.1371,
      address: 'Barrio de Cuevas 12, 18500 Guadix',
      pricePerNight: 175,
      currency: 'EUR',
      maxGuests: 6,
      bedrooms: 3,
      beds: 3,
      bathrooms: 2,
      propertyType: 'House',
      category: 'Caves',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Air conditioning', 'Mountain view', 'Courtyard', 'Parking', 'Eco-friendly', 'Authentic architecture'],
      houseRules: 'No smoking, No pets, Respectful of neighbors',
      cancellationPolicy: 'Flexible: Full refund 2 days prior to arrival',
      minimumStay: 2,
      maximumStay: 21,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200&h=800&fit=crop', caption: 'Cave Entrance', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&h=800&fit=crop', caption: 'Cave Living Room', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=1200&h=800&fit=crop', caption: 'Courtyard', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=1200&h=800&fit=crop', caption: 'Cave Kitchen', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 156,
      createdAt: '2024-11-05T10:00:00Z',
      updatedAt: '2024-12-07T13:20:00Z'
    },
    // Castles
    {
      publicId: 'lst-025',
      landlordPublicId: 'usr-025',
      title: 'Medieval Castle in the Scottish Highlands',
      description: 'Live like royalty in this authentic 12th-century castle complete with turrets, great halls, and sweeping Highland views. The castle has been carefully restored with modern amenities while preserving its historic character. Features include a grand dining hall, library, and expansive grounds perfect for events.',
      location: 'Inverness',
      city: 'Inverness',
      country: 'Scotland',
      latitude: 57.4778,
      longitude: -4.2247,
      address: 'Castle Road, Inverness IV2 3HG',
      pricePerNight: 2800,
      currency: 'GBP',
      maxGuests: 18,
      bedrooms: 9,
      beds: 12,
      bathrooms: 7,
      propertyType: 'House',
      category: 'Castles',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Fireplace', 'Highland view', 'Parking', 'Library', 'Great hall', 'Historic grounds', 'Event space', 'Staff available'],
      houseRules: 'No smoking, Respect historic property, Events allowed with approval',
      cancellationPolicy: 'Strict: 50% refund up to 60 days before check-in',
      minimumStay: 3,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1200&h=800&fit=crop', caption: 'Castle Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1563622825-5f9aa97ee1ba?w=1200&h=800&fit=crop', caption: 'Great Hall', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=1200&h=800&fit=crop', caption: 'Highland Views', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=1200&h=800&fit=crop', caption: 'Tower Room', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 41,
      createdAt: '2024-11-08T12:00:00Z',
      updatedAt: '2024-12-08T14:00:00Z'
    },
    {
      publicId: 'lst-026',
      landlordPublicId: 'usr-026',
      title: 'Romantic Castle Tower in Germany',
      description: 'Stay in a fairy-tale castle tower along the Rhine River. This intimate property offers stunning river views, medieval architecture, and romantic ambiance. Perfect for couples seeking a unique getaway. The tower features period furnishings, a four-poster bed, and access to the castle grounds and wine cellars.',
      location: 'Rhine Valley',
      city: 'Koblenz',
      country: 'Germany',
      latitude: 50.3569,
      longitude: 7.5890,
      address: 'Rheinuferstrasse 100, 56068 Koblenz',
      pricePerNight: 485,
      currency: 'EUR',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Castles',
      amenities: ['WiFi', 'Heating', 'River view', 'Wine cellar', 'Historic grounds', 'Four-poster bed', 'Fireplace', 'Medieval architecture'],
      houseRules: 'No smoking, Romantic retreat - adults only, Respect historic property',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 2,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1565130838609-c3a86655db61?w=1200&h=800&fit=crop', caption: 'Castle Tower', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&h=800&fit=crop', caption: 'Rhine View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1543489822-c49534f3271f?w=1200&h=800&fit=crop', caption: 'Medieval Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop', caption: 'Wine Cellar', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1565130838609-c3a86655db61?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 88,
      createdAt: '2024-11-10T13:00:00Z',
      updatedAt: '2024-12-09T11:30:00Z'
    },
    // Skiing
    {
      publicId: 'lst-027',
      landlordPublicId: 'usr-027',
      title: 'Ski-In/Ski-Out Chalet in Whistler',
      description: 'Hit the slopes directly from this luxury ski chalet in Whistler. This prime location offers true ski-in/ski-out access, with the gondola just steps away. Features include a hot tub, sauna, ski storage with boot warmers, and panoramic mountain views. Perfect for serious skiers and snowboarders.',
      location: 'Whistler',
      city: 'Whistler',
      country: 'Canada',
      latitude: 50.1163,
      longitude: -122.9574,
      address: 'Blackcomb Way 200, Whistler, BC V8E 0X1',
      pricePerNight: 1450,
      currency: 'CAD',
      maxGuests: 10,
      bedrooms: 5,
      beds: 6,
      bathrooms: 5,
      propertyType: 'Chalet',
      category: 'Skiing',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Mountain view', 'Hot tub', 'Sauna', 'Ski storage', 'Boot warmers', 'Fireplace', 'Parking', 'Ski-in/Ski-out'],
      houseRules: 'No smoking, Ski equipment care required, Quiet hours 10 PM - 8 AM',
      cancellationPolicy: 'Strict: 50% refund up to 30 days before check-in',
      minimumStay: 4,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1605538399941-c88b6500e09a?w=1200&h=800&fit=crop', caption: 'Ski Chalet', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1551524481-93dc270c2d82?w=1200&h=800&fit=crop', caption: 'Slope Access', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1200&h=800&fit=crop', caption: 'Mountain View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?w=1200&h=800&fit=crop', caption: 'Hot Tub', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1605538399941-c88b6500e09a?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 124,
      createdAt: '2024-11-12T09:00:00Z',
      updatedAt: '2024-12-08T16:00:00Z'
    },
    {
      publicId: 'lst-028',
      landlordPublicId: 'usr-028',
      title: 'Alpine Ski Lodge in the French Alps',
      description: 'Experience authentic Alpine living in this traditional ski lodge in Chamonix. Located at the base of Mont Blanc, this charming property offers easy access to world-class skiing, hiking, and mountaineering. Features include a stone fireplace, rustic beams, and a terrace with glacier views.',
      location: 'Chamonix',
      city: 'Chamonix',
      country: 'France',
      latitude: 45.9237,
      longitude: 6.8694,
      address: 'Route des Pèlerins 88, 74400 Chamonix',
      pricePerNight: 825,
      currency: 'EUR',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 3,
      propertyType: 'Chalet',
      category: 'Skiing',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Mountain view', 'Fireplace', 'Ski storage', 'Parking', 'Terrace', 'Sauna', 'Boot warmers'],
      houseRules: 'No smoking, Mountaineering equipment care required, Bear-safe food storage',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 3,
      maximumStay: 21,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=800&fit=crop', caption: 'Alpine Lodge', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop', caption: 'Mont Blanc View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=1200&h=800&fit=crop', caption: 'Rustic Interior', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=1200&h=800&fit=crop', caption: 'Cozy Fireplace', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 97,
      createdAt: '2024-11-15T10:00:00Z',
      updatedAt: '2024-12-09T12:00:00Z'
    },
    // Camping
    {
      publicId: 'lst-029',
      landlordPublicId: 'usr-029',
      title: 'Luxury Safari Tent in Yosemite',
      description: 'Glamp in style at this luxury safari tent with stunning views of Yosemite Valley. Features a king-size bed, en-suite bathroom, heating, and a private deck. Experience the great outdoors without sacrificing comfort. Perfect for nature lovers who appreciate modern amenities.',
      location: 'Yosemite',
      city: 'Yosemite',
      country: 'United States',
      latitude: 37.8651,
      longitude: -119.5383,
      address: 'Yosemite Valley Road, Yosemite, CA 95389',
      pricePerNight: 375,
      currency: 'USD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Camping',
      amenities: ['WiFi', 'Heating', 'Valley view', 'Private deck', 'Outdoor shower', 'Campfire pit', 'Hiking access', 'Eco-friendly', 'Stargazing'],
      houseRules: 'No smoking, Wildlife safety protocols, Leave no trace principles',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=1200&h=800&fit=crop', caption: 'Safari Tent', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop', caption: 'Tent Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=1200&h=800&fit=crop', caption: 'Valley View', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=1200&h=800&fit=crop', caption: 'Private Deck', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 167,
      createdAt: '2024-11-18T11:00:00Z',
      updatedAt: '2024-12-07T15:30:00Z'
    },
    {
      publicId: 'lst-030',
      landlordPublicId: 'usr-030',
      title: 'Glamping Dome in New Zealand',
      description: 'Sleep under the stars in this transparent glamping dome surrounded by New Zealand\'s pristine wilderness. Watch the Southern Cross constellation from your bed, wake up to birdsong, and explore nearby hiking trails. The dome includes a comfortable bed, heating, and a kitchenette.',
      location: 'Queenstown',
      city: 'Queenstown',
      country: 'New Zealand',
      latitude: -45.0312,
      longitude: 168.6626,
      address: 'Mountain Road 234, Queenstown 9300',
      pricePerNight: 295,
      currency: 'NZD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Camping',
      amenities: ['WiFi', 'Heating', 'Mountain view', 'Stargazing', 'Hiking access', 'Kitchenette', 'Eco-friendly', 'Outdoor seating', 'Campfire pit'],
      houseRules: 'No smoking, Eco-friendly practices required, Wildlife respect',
      cancellationPolicy: 'Flexible: Full refund 2 days prior to arrival',
      minimumStay: 1,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop', caption: 'Glamping Dome', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=1200&h=800&fit=crop', caption: 'Starry Night', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1537905569824-f89f14cceb68?w=1200&h=800&fit=crop', caption: 'Dome Interior', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop', caption: 'Wilderness View', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 189,
      createdAt: '2024-11-20T12:00:00Z',
      updatedAt: '2024-12-08T13:00:00Z'
    },
    // Luxe
    {
      publicId: 'lst-031',
      landlordPublicId: 'usr-031',
      title: 'Penthouse Suite with Burj Khalifa View',
      description: 'Experience the height of luxury in this ultra-modern penthouse with panoramic views of the Burj Khalifa and Dubai skyline. Features include a private infinity pool, home automation, designer furnishings, and 24/7 concierge service. This property defines opulent urban living.',
      location: 'Downtown Dubai',
      city: 'Dubai',
      country: 'United Arab Emirates',
      latitude: 25.1972,
      longitude: 55.2744,
      address: 'Sheikh Mohammed bin Rashid Blvd, Dubai',
      pricePerNight: 3200,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 3,
      bathrooms: 4,
      propertyType: 'Apartment',
      category: 'Luxe',
      amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Burj Khalifa view', 'Concierge', 'Gym', 'Spa', 'Valet parking', 'Smart home', 'Butler service', 'Wine cellar'],
      houseRules: 'No smoking, No parties, Dubai regulations apply',
      cancellationPolicy: 'Strict: 50% refund up to 30 days before check-in',
      minimumStay: 3,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop', caption: 'Penthouse View', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=1200&h=800&fit=crop', caption: 'Burj Khalifa', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1200&h=800&fit=crop', caption: 'Luxury Interior', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1605346434674-a440ca4dc4c0?w=1200&h=800&fit=crop', caption: 'Infinity Pool', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 52,
      createdAt: '2024-11-22T13:00:00Z',
      updatedAt: '2024-12-09T14:30:00Z'
    },
    {
      publicId: 'lst-032',
      landlordPublicId: 'usr-032',
      title: 'Monaco Yacht Club Residence',
      description: 'Live the Monaco lifestyle in this prestigious apartment overlooking the yacht club and Mediterranean. This exclusive property features marble floors, designer furniture, a private terrace, and access to luxury amenities. Walking distance to the casino, F1 circuit, and finest restaurants.',
      location: 'Monte Carlo',
      city: 'Monaco',
      country: 'Monaco',
      latitude: 43.7384,
      longitude: 7.4246,
      address: 'Avenue Princesse Grace, 98000 Monaco',
      pricePerNight: 2850,
      currency: 'EUR',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 3,
      propertyType: 'Apartment',
      category: 'Luxe',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Sea view', 'Concierge', 'Parking', 'Gym', 'Pool', 'Security', 'Marble finishes', 'Designer furniture'],
      houseRules: 'No smoking, Dress code for building amenities, Monaco regulations',
      cancellationPolicy: 'Strict: 50% refund up to 60 days before check-in',
      minimumStay: 5,
      maximumStay: 30,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop', caption: 'Monaco View', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1567225591450-4b6e7d188ea6?w=1200&h=800&fit=crop', caption: 'Yacht Club', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&h=800&fit=crop', caption: 'Luxury Living', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=1200&h=800&fit=crop', caption: 'Terrace', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 36,
      createdAt: '2024-11-25T14:00:00Z',
      updatedAt: '2024-12-08T16:45:00Z'
    },
    // Tiny homes
    {
      publicId: 'lst-033',
      landlordPublicId: 'usr-033',
      title: 'Minimalist Tiny House on Wheels',
      description: 'Experience tiny living in this beautifully designed mobile tiny house. Despite its compact 280 sq ft, the space feels open and airy with clever storage, a loft bedroom, full kitchen, and bathroom. Perfect for those interested in minimalist living and sustainable design.',
      location: 'Portland',
      city: 'Portland',
      country: 'United States',
      latitude: 45.5152,
      longitude: -122.6784,
      address: 'Tiny House Village, Portland, OR 97214',
      pricePerNight: 125,
      currency: 'USD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Tiny homes',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Air conditioning', 'Workspace', 'Eco-friendly', 'Solar power', 'Composting toilet', 'Smart storage'],
      houseRules: 'No smoking, Minimalist living principles, Eco-friendly practices',
      cancellationPolicy: 'Flexible: Full refund 2 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1566304463940-3e9dd7d8c65d?w=1200&h=800&fit=crop', caption: 'Tiny House', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&h=800&fit=crop', caption: 'Efficient Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop', caption: 'Loft Bedroom', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=1200&h=800&fit=crop', caption: 'Compact Kitchen', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1566304463940-3e9dd7d8c65d?w=1200&h=800&fit=crop',
      averageRating: 4.8,
      totalReviews: 214,
      createdAt: '2024-11-28T10:00:00Z',
      updatedAt: '2024-12-09T08:30:00Z'
    },
    {
      publicId: 'lst-034',
      landlordPublicId: 'usr-034',
      title: 'Off-Grid Tiny Cabin in the Woods',
      description: 'Disconnect and recharge in this charming off-grid tiny cabin surrounded by forest. Solar-powered with rainwater collection, this 200 sq ft retreat proves tiny living can be comfortable. Features include a wood stove, outdoor shower, and a deck perfect for morning coffee and wildlife watching.',
      location: 'Asheville',
      city: 'Asheville',
      country: 'United States',
      latitude: 35.5951,
      longitude: -82.5515,
      address: 'Forest Road 456, Asheville, NC 28801',
      pricePerNight: 145,
      currency: 'USD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'Cabin',
      category: 'Tiny homes',
      amenities: ['Forest view', 'Wood stove', 'Outdoor shower', 'Deck', 'Solar power', 'Eco-friendly', 'Hiking access', 'Off-grid', 'Stargazing'],
      houseRules: 'No smoking, Off-grid living practices, Wildlife safety, Pack it in/pack it out',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&h=800&fit=crop', caption: 'Forest Cabin', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=1200&h=800&fit=crop', caption: 'Tiny Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200&h=800&fit=crop', caption: 'Wood Stove', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop', caption: 'Forest Deck', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 178,
      createdAt: '2024-11-30T11:00:00Z',
      updatedAt: '2024-12-08T10:15:00Z'
    },
    // Treehouses
    {
      publicId: 'lst-035',
      landlordPublicId: 'usr-035',
      title: 'Luxury Treehouse in Costa Rica Rainforest',
      description: 'Sleep among the treetops in this spectacular treehouse suspended in the Costa Rican rainforest canopy. Wake up to howler monkeys, toucans, and sloths. The treehouse features a rope bridge entrance, panoramic windows, an outdoor shower, and a private deck. An unforgettable eco-adventure.',
      location: 'Monteverde',
      city: 'Monteverde',
      country: 'Costa Rica',
      latitude: 10.3046,
      longitude: -84.8250,
      address: 'Cloud Forest Road, Monteverde 60109',
      pricePerNight: 385,
      currency: 'USD',
      maxGuests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Treehouses',
      amenities: ['WiFi', 'Kitchen', 'Rainforest view', 'Wildlife viewing', 'Outdoor shower', 'Rope bridge', 'Eco-friendly', 'Hiking access', 'Stargazing'],
      houseRules: 'No smoking, Respect wildlife, Treehouse safety guidelines',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1503652601-557d07733ddc?w=1200&h=800&fit=crop', caption: 'Treehouse Exterior', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1200&h=800&fit=crop', caption: 'Canopy View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1511593358241-7eea1f3c84e5?w=1200&h=800&fit=crop', caption: 'Interior Living', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&h=800&fit=crop', caption: 'Rope Bridge', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1503652601-557d07733ddc?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 241,
      createdAt: '2024-12-01T10:00:00Z',
      updatedAt: '2024-12-09T09:00:00Z'
    },
    {
      publicId: 'lst-036',
      landlordPublicId: 'usr-036',
      title: 'Modern Treehouse Retreat in the Pacific Northwest',
      description: 'Experience treehouse living reimagined in this contemporary design. Perched 30 feet high among ancient cedars, this architectural gem features floor-to-ceiling windows, a suspended walkway, and a spiral staircase. Modern amenities meet forest serenity in this unique Pacific Northwest retreat.',
      location: 'Olympic Peninsula',
      city: 'Seattle',
      country: 'United States',
      latitude: 47.8021,
      longitude: -123.5269,
      address: 'Forest Drive 789, Olympic Peninsula, WA 98363',
      pricePerNight: 425,
      currency: 'USD',
      maxGuests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
      propertyType: 'House',
      category: 'Treehouses',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Forest view', 'Hot tub', 'Fireplace', 'Eco-friendly', 'Modern design', 'Hiking access'],
      houseRules: 'No smoking, No pets, Respect forest environment',
      cancellationPolicy: 'Moderate: Full refund 5 days prior to arrival',
      minimumStay: 2,
      maximumStay: 7,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=800&fit=crop', caption: 'Modern Treehouse', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&h=800&fit=crop', caption: 'Forest Canopy', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=800&fit=crop', caption: 'Suspended Walkway', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&h=800&fit=crop', caption: 'Interior Design', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 187,
      createdAt: '2024-12-03T11:00:00Z',
      updatedAt: '2024-12-09T10:30:00Z'
    },
    // Farms
    {
      publicId: 'lst-037',
      landlordPublicId: 'usr-037',
      title: 'Working Vineyard Estate in Tuscany',
      description: 'Live the Italian dream at this authentic working vineyard in the heart of Tuscany. The restored farmhouse offers panoramic views of rolling hills and vineyards. Participate in wine-making, enjoy farm-to-table meals, and explore medieval towns. Includes wine tasting and cooking classes.',
      location: 'Chianti',
      city: 'Florence',
      country: 'Italy',
      latitude: 43.5465,
      longitude: 11.2605,
      address: 'Via del Vino 50, 50022 Chianti',
      pricePerNight: 625,
      currency: 'EUR',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 3,
      propertyType: 'House',
      category: 'Farms',
      amenities: ['WiFi', 'Kitchen', 'Pool', 'Vineyard view', 'Wine cellar', 'Cooking classes', 'Wine tasting', 'Olive grove', 'Farm animals', 'Parking'],
      houseRules: 'No smoking indoors, Respect working farm, Participation welcome',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 3,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=1200&h=800&fit=crop', caption: 'Tuscan Farmhouse', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&h=800&fit=crop', caption: 'Vineyard Views', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&h=800&fit=crop', caption: 'Wine Cellar', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&h=800&fit=crop', caption: 'Farmhouse Interior', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 156,
      createdAt: '2024-12-04T12:00:00Z',
      updatedAt: '2024-12-09T11:45:00Z'
    },
    {
      publicId: 'lst-038',
      landlordPublicId: 'usr-038',
      title: 'Organic Farm Cottage in Vermont',
      description: 'Experience sustainable farm living in this charming cottage on a certified organic farm. Collect fresh eggs, pick vegetables, and learn about regenerative agriculture. The property includes a wood stove, farmhouse kitchen, and views of pastures and mountains. Perfect for families and food enthusiasts.',
      location: 'Stowe',
      city: 'Stowe',
      country: 'United States',
      latitude: 44.4654,
      longitude: -72.6874,
      address: 'Farm Road 234, Stowe, VT 05672',
      pricePerNight: 235,
      currency: 'USD',
      maxGuests: 6,
      bedrooms: 3,
      beds: 4,
      bathrooms: 2,
      propertyType: 'Cottage',
      category: 'Farms',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'Mountain view', 'Farm animals', 'Organic garden', 'Fresh eggs', 'Wood stove', 'Hiking access', 'Parking'],
      houseRules: 'No smoking, Farm safety rules, Children must be supervised around animals',
      cancellationPolicy: 'Flexible: Full refund 3 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop', caption: 'Farm Cottage', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1200&h=800&fit=crop', caption: 'Pastoral View', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=1200&h=800&fit=crop', caption: 'Farm Animals', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop', caption: 'Cozy Interior', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 198,
      createdAt: '2024-12-05T10:00:00Z',
      updatedAt: '2024-12-09T12:15:00Z'
    },
    // Historical homes
    {
      publicId: 'lst-039',
      landlordPublicId: 'usr-039',
      title: 'Colonial-Era Mansion in Charleston',
      description: 'Step back in time in this meticulously restored 1780s mansion in Charleston\'s historic district. Original details include crown molding, heart pine floors, and marble fireplaces. The property features period furnishings, a formal garden, and modern conveniences discreetly integrated. A living museum.',
      location: 'Historic District',
      city: 'Charleston',
      country: 'United States',
      latitude: 32.7765,
      longitude: -79.9311,
      address: 'Meeting Street 100, Charleston, SC 29401',
      pricePerNight: 875,
      currency: 'USD',
      maxGuests: 10,
      bedrooms: 5,
      beds: 6,
      bathrooms: 4,
      propertyType: 'House',
      category: 'Historical homes',
      amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Historic district', 'Formal garden', 'Library', 'Period furnishings', 'Fireplace', 'Parking', 'Event space'],
      houseRules: 'No smoking, Respect historic property, Events allowed with approval',
      cancellationPolicy: 'Strict: 50% refund up to 14 days before check-in',
      minimumStay: 3,
      maximumStay: 21,
      instantBook: false,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&h=800&fit=crop', caption: 'Colonial Mansion', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=1200&h=800&fit=crop', caption: 'Historic Interior', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&h=800&fit=crop', caption: 'Formal Garden', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Period Details', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&h=800&fit=crop',
      averageRating: 5.0,
      totalReviews: 89,
      createdAt: '2024-12-06T13:00:00Z',
      updatedAt: '2024-12-09T13:30:00Z'
    },
    {
      publicId: 'lst-040',
      landlordPublicId: 'usr-040',
      title: 'Victorian Manor in San Francisco',
      description: 'Experience the grandeur of the Gilded Age in this stunning 1890s Victorian manor. Original stained glass, ornate woodwork, and period wallpapers have been lovingly preserved. The property includes a turret room, parlor, formal dining room, and a garden with city views. Featured in architectural tours.',
      location: 'Pacific Heights',
      city: 'San Francisco',
      country: 'United States',
      latitude: 37.7913,
      longitude: -122.4363,
      address: 'Broadway 2000, San Francisco, CA 94115',
      pricePerNight: 725,
      currency: 'USD',
      maxGuests: 8,
      bedrooms: 4,
      beds: 5,
      bathrooms: 3,
      propertyType: 'House',
      category: 'Historical homes',
      amenities: ['WiFi', 'Kitchen', 'Heating', 'City view', 'Turret room', 'Stained glass', 'Historic district', 'Garden', 'Parking', 'Period furnishings'],
      houseRules: 'No smoking, No parties, Respect Victorian features',
      cancellationPolicy: 'Moderate: Full refund 7 days prior to arrival',
      minimumStay: 2,
      maximumStay: 14,
      instantBook: true,
      status: ListingStatus.ACTIVE,
      images: [
        { url: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=1200&h=800&fit=crop', caption: 'Victorian Facade', isCover: true, sortOrder: 1 },
        { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop', caption: 'Stained Glass', isCover: false, sortOrder: 2 },
        { url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&h=800&fit=crop', caption: 'Grand Parlor', isCover: false, sortOrder: 3 },
        { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=800&fit=crop', caption: 'Turret Room', isCover: false, sortOrder: 4 }
      ],
      coverImageUrl: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=1200&h=800&fit=crop',
      averageRating: 4.9,
      totalReviews: 112,
      createdAt: '2024-12-07T14:00:00Z',
      updatedAt: '2024-12-09T14:45:00Z'
    }
  ];

  constructor() {}

  // Mock implementation of search listings
  searchListings(searchParams: SearchListingParams): Observable<ApiResponse<ListingPage>> {
    let filteredListings = [...this.mockListings];

    // Apply filters
    if (searchParams.location) {
      filteredListings = filteredListings.filter(l => 
        l.location.toLowerCase().includes(searchParams.location!.toLowerCase()) ||
        l.city.toLowerCase().includes(searchParams.location!.toLowerCase())
      );
    }

    if (searchParams.city) {
      filteredListings = filteredListings.filter(l => 
        l.city.toLowerCase() === searchParams.city!.toLowerCase()
      );
    }

    if (searchParams.categories && searchParams.categories.length > 0) {
      filteredListings = filteredListings.filter(l => 
        searchParams.categories!.includes(l.category)
      );
    }

    if (searchParams.propertyTypes && searchParams.propertyTypes.length > 0) {
      filteredListings = filteredListings.filter(l => 
        searchParams.propertyTypes!.includes(l.propertyType)
      );
    }

    if (searchParams.minPrice) {
      filteredListings = filteredListings.filter(l => l.pricePerNight >= searchParams.minPrice!);
    }

    if (searchParams.maxPrice) {
      filteredListings = filteredListings.filter(l => l.pricePerNight <= searchParams.maxPrice!);
    }

    if (searchParams.guests) {
      filteredListings = filteredListings.filter(l => l.maxGuests >= searchParams.guests!);
    }

    if (searchParams.minBedrooms) {
      filteredListings = filteredListings.filter(l => l.bedrooms >= searchParams.minBedrooms!);
    }

    if (searchParams.minBathrooms) {
      filteredListings = filteredListings.filter(l => l.bathrooms >= searchParams.minBathrooms!);
    }

    if (searchParams.amenities && searchParams.amenities.length > 0) {
      filteredListings = filteredListings.filter(l => 
        searchParams.amenities!.every(amenity => l.amenities.includes(amenity))
      );
    }

    if (searchParams.instantBook) {
      filteredListings = filteredListings.filter(l => l.instantBook);
    }

    // Pagination
    const page = searchParams.page || 0;
    const size = searchParams.size || 20;
    const start = page * size;
    const end = start + size;
    const paginatedListings = filteredListings.slice(start, end);

    const response: ApiResponse<ListingPage> = {
      success: true,
      message: 'Listings retrieved successfully',
      timestamp: new Date().toISOString(),
      data: {
        content: paginatedListings,
        number: page,
        size: size,
        totalElements: filteredListings.length,
        totalPages: Math.ceil(filteredListings.length / size),
        first: page === 0,
        last: end >= filteredListings.length,
        empty: filteredListings.length === 0
      }
    };

    return of(response); // Removed delay for immediate response
  }

  // Mock implementation of get listing by ID
  getListingById(publicId: string): Observable<ApiResponse<Listing>> {
    const listing = this.mockListings.find(l => l.publicId === publicId);
    
    const response: ApiResponse<Listing> = {
      success: !!listing,
      message: listing ? 'Listing retrieved successfully' : 'Listing not found',
      timestamp: new Date().toISOString(),
      data: listing || null as any
    };

    return of(response); // Removed delay for immediate response
  }

  // Mock implementation of get all listings
  getAllListings(
    page: number = 0,
    size: number = 20,
    sortBy: string = 'createdAt',
    sortDirection: string = 'DESC'
  ): Observable<ApiResponse<ListingPage>> {
    return this.searchListings({ page, size, sortBy, sortDirection });
  }

  // Get listings by category
  getListingsByCategory(
    category: string,
    page: number = 0,
    size: number = 20
  ): Observable<ApiResponse<ListingPage>> {
    return this.searchListings({ categories: [category], page, size });
  }
}
